# Generated by Django 5.0.6 on 2024-06-01 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_alter_recipe_detail"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipe",
            name="ingredients",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="name",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="tags",
            field=models.CharField(max_length=50),
        ),
    ]
